# Generated by Django 5.0.2 on 2024-03-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_eliminar_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
