# Generated by Django 5.0.2 on 2024-03-25 05:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_paciente_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
