# Generated by Django 5.0.2 on 2024-03-29 03:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
